# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M.', 'M.'), ('Mme', 'Mme'), ('SARL', 'SARL')], default='M.', max_length=10)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('cp', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('add_description', models.TextField(blank=True, max_length=400, null=True)),
                ('acompteht', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acomptettc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prixht', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prixttc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dejaregle', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parttva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('netapayer', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='FactureStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(max_length=255)),
                ('step_description', models.TextField(max_length=500)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp.Facture')),
            ],
        ),
        migrations.CreateModel(
            name='Tva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp.Tva'),
        ),
    ]
