# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minierp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('add_description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevisStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(max_length=255)),
                ('step_description', models.TextField(max_length=500)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp.Devis')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='civilite',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme', 'Mme'), ('M. et Mme', 'M. et Mme'), ('SARL', 'SARL')], default='M.', max_length=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='acompteht',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='facture',
            name='acomptettc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dejaregle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='facture',
            name='netapayer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='facture',
            name='parttva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='facture',
            name='prixht',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='facture',
            name='prixttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='devis',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp.Client'),
        ),
    ]
