# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minierp', '0002_auto_20170313_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devisstep',
            old_name='facture',
            new_name='devis',
        ),
    ]
